coverage:
  status:
    project:
      default: false
      UnitTest:
        target: 80%
        threshold: 1%
        flags:
          - UnitTest
comment:
  layout: 'header, diff, flags, files, footer'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
